# A docker image supplied by nf-core. 
# Defined at https://github.com/nf-core/tools/blob/main/nf_core/gitpod/gitpod.Dockerfile
# Image contains:
# - git
# - conda
# - docker
# - apptainer
# - nextflow
# - nf-core (tools)
# - nf-test
image: nfcore/gitpod:latest

tasks:
  - name: Init Conda and Install Pixi
    command: |
      sudo chown gitpod -R /home/gitpod/
      # Conda setup
      export CONDA_ENVS_PATH=/workspace/conda/envs
      conda config --set repodata_threads 4
      conda config --set auto_activate_base false
      conda config --remove channels defaults
      conda init
      conda env create -f tutorials/jupyter/environment.yml
      conda env create -f tutorials/nextflow/environment.yml
      conda env create -f tutorials/quarto/environment.yml
      conda env create -f tutorials/snakemake/environment.yml
      # Install Pixi
      curl -fsSL https://pixi.sh/install.sh | bash
      . /home/gitpod/.bashrc
      echo sourced /home/gitpod/.bashrc
      conda env list
  - name: Update Nextflow
    command: |
      nextflow self-update
      exit

vscode:
  extensions:
    - nextflow.nextflow
    - snakemake.snakemake-lang
    - quarto.quarto
