---
title: "Contents"
subtitle: "Tutorials and lecture links"
pagetitle: "Contents | Tools for Reproducible Research"
description: ""
date: ""
toc: false
number-sections: false
sidebar: false
format: html
---

Below you can find a list of all the topics covered by the workshop and links to
their respective tutorials and lectures. Please note that not all topics have a
tutorial associated with them, and are only covered by a lecture. Lectures
should be considered short introductions to each topic, while the tutorials
themselves contain all of the material covered by the workshop.

<br>

| Topic                   | Instructor     | Lecture                                                                          | Tutorial                                           |
| ----------------------- | :------------- | :------------------------------------------------------------------------------: | :------------------------------------------------: |
| Introduction            | Erik Fasterius | [{{< fa file-lines >}}](lectures/introduction/introduction.html)                 | [{{< fa file-lines >}}](pages/introduction.html)   |
| Data management         | John Sundh     | [{{< fa file-lines >}}](lectures/data-management/data-management.html)           |                                                    |
| Git                     | Erik Fasterius | [{{< fa file-lines >}}](lectures/git/git.html)                                   | [{{< fa file-lines >}}](pages/git.html)            |
| Conda                   | John Sundh     | [{{< fa file-lines >}}](lectures/conda/conda.html)                               | [{{< fa file-lines >}}](pages/conda.html)          |
| Containers              | Erik Fasterius | [{{< fa file-lines >}}](lectures/containers/containers.html)                     | [{{< fa file-lines >}}](pages/containers.html)     |
| Quarto                  | Erik Fasterius | [{{< fa file-lines >}}](lectures/quarto/quarto.html)                             | [{{< fa file-lines >}}](pages/quarto.html)         |
| Jupyter                 | John Sundh     | [{{< fa file-lines >}}](lectures/jupyter/jupyter.html)                           | [{{< fa file-lines >}}](pages/jupyter.html)        |
| Snakemake               | John Sundh     | [{{< fa file-lines >}}](lectures/snakemake/snakemake.html)                       | [{{< fa file-lines >}}](pages/snakemake.html)      |
| Nextflow                | Erik Fasterius | [{{< fa file-lines >}}](lectures/nextflow/nextflow.html)                         | [{{< fa file-lines >}}](pages/nextflow.html)       |
| Documentation           | Erik Fasterius | [{{< fa file-lines >}}](lectures/documentation/documentation.html)               | [{{< fa file-lines >}}](pages/documentation.html)  |
| Putting it all together | Erik Fasterius | [{{< fa file-lines >}}](lectures/putting-it-together/putting-it-together.html)   |                                                    |
| Markdown                | Erik Fasterius |                                                                                  | [{{< fa file-lines >}}](pages/markdown.html)       |
| Take-down               | Erik Fasterius |                                                                                  | [{{< fa file-lines >}}](pages/take-down.html)      |
