channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - fastqc
  - seqtk
  - snakemake
  - multiqc
  - jupyter
  - bowtie2
  - tbb
  - samtools
  - subread
  - bedtools
  - r-base
  - r-ggplot2
  - r-reshape2
  - r-stringi
  - r-pheatmap
  - r-rmarkdown
  - r-r.utils
  - bioconductor-rtracklayer
  - bioconductor-geoquery
  - wget
  - graphviz
  - xorg-libxrender
  - xorg-libxpm
