channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools
  - bioconductor-geoquery
  - bioconductor-rtracklayer
  - bowtie2
  - fastqc
  - graphviz
  - jupyter
  - multiqc
  - python
  - quarto
  - r-base
  - r-ggplot2
  - r-pheatmap
  - r-r.utils
  - r-reshape2
  - r-rmarkdown
  - r-stringi
  - samtools
  - seqtk
  - snakemake>=8
  - subread>=2
  - tbb
  - wget
  - xorg-libxpm
  - xorg-libxrender
