::: {.callout-note}

## Address

Room Sven Gardel; BMC D1513a  
BMC, Hus D
Sölvegatan 19
223 62 Lund  
Sweden  

**It is located in the BMC D Building on the 15th floor**

:::

Few selected hotels are listed below ranked by distance from the venue.

- [Elite Hotel Ideon](https://www.elite.se/hotell/lund/elite-hotel-ideon-lund/) (1.1 km, 15 min walk)
- [Hotel Lundia](https://www.hotellundia.se/) (1.3 km, 16 min walk)
- [Grand Hotel Lund](https://www.grandlund.se/) (1.4 km, 18 min walk)
- [Motel L](https://ligula.se/motel-l/motel-l-lund/) (2.2 km, 30 min walk)

The venue and hotels are also marked on the map.

For Lund city buses, tram, regional buses and regional trains, use [skanetrafiken.se](https://www.skanetrafiken.se/). You can buy a ticket at the central station in Lund or at the regional bus (card only). You can also use the app [Skånetrafiken](https://www.skanetrafiken.se/biljetter/app2/) From the Lund C the easiest is to take the tram from **Clemenstorget** towards **ESS** and get off at  **Lund LTH**. The trip take about 4 minutes and a tram leaves about four times an hour.

#### Lunch

The lunches during the course will be provided at **Cafe Bryggan** located at the **IKDC** building which is a 10 minute walk from the course. The restaurant menu can be found [here](https://mersmak.me/vara-stallen/bryggan/).

#### Dinner

The course dinner on the **21st of April at 18:00** will be at [Restaurang Mediterranean](https://www.mediterranean.se/). We will walk together from the course venue at 17:15; see the location on this [map](https://maps.app.goo.gl/6hbmvLqQdmbgvgcq5).
