name: quarto-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - quarto
  - jupyter
  - python=3
  - r-base
  - r-ggplot2
  - r-palmerpenguins
  - r-rmarkdown
  - r-reticulate
  - nb_conda_kernels
  - papermill