---
output:
  pdf_document:
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      fig.height=7, 
                      fig.width=6, 
                      fig.align='center', 
                      fig.pos="ht",
                      eval.after="fig.cap")
library(ggplot2)
library(knitr)
```

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

# Supplementary Methods

We took the sample files and analyzed them.

\newpage

```{r}
kable(head(iris,15), caption="Test", )
```


```{r, fig.cap=paste("A scatterplot with",length(tmp),"points.")}
tmp <- data.frame(x=runif(100), y=runif(100))
p1 <- ggplot(tmp, aes(x=x, y=y)) +
  geom_point()
multiplot(plotlist=list(p1,p1), layout=cbind(1,1,2))
```

\newpage

```{r, fig.cap=paste("A boxplot. The average is",round(mean(tmp2)),".")}
tmp2 <- runif(100)*100
boxplot(tmp2)
```

